### ISSUE TITLE
Add a symptom tracker

### ISSUE THREAD

**Issue by Lifespark-Technologies** [Lifespark-Technologies/Infomed#39] opened 2020-05-16 16:50 UTC

**Comment by bl-nero** [comment] 2020-05-18 20:22
Duplicates #13 .

**Comment by bl-nero** [comment] 2020-05-20 11:04
Duplicate of #13 .

**Comment by bl-nero** [comment] 2020-05-20 11:04
Duplicate of #13 .

**Comment by bl-nero** [comment] 2020-05-20 11:06
Duplicate of #13

**Closed by bl-nero** 2020-05-20 11:06 UTC
